<?php
/**
 * FieldDocs: how the reference documents describe a field and an operation
 *
 * @package SEOCart
 * @since   0.1.0
 * @license GPL-3.0-or-later
 */

declare( strict_types=1 );

namespace SEOCart\Tools\Docs;

use SEOCart\Application\Operations\OperationDefinition;
use SEOCart\Interfaces\Operations\OperationInvoker;
use SEOCart\Support\Error\ErrorCode;
use SEOCart\Support\Error\ErrorTable;
use SEOCart\Support\Schema\FieldSpec;
use SEOCart\Support\Schema\FieldType;
use SEOCart\Support\Schema\Privacy;

/**
 * Writes the English sentences the Abilities and WP-CLI references share.
 *
 * This class owns one fact: how a generated reference document words a field's type,
 * constraints, default and privacy, and an operation's capability and error codes. Both markdown
 * references read it, so the same field is described the same way in both, and the output is
 * already in the form Prettier leaves unchanged. errorCodes() is also the OpenAPI document's list
 * of an operation's codes, so every document lists the same ones.
 *
 * @since 0.1.0
 */
final class FieldDocs {

	/**
	 * The notice a generated document starts with.
	 *
	 * @since 0.1.0
	 *
	 * @param string $source What the document is generated from.
	 * @return string An HTML comment for the top of a markdown file.
	 */
	public static function generatedNotice( string $source ): string {
		return '<!-- Generated by `' . DocsRunner::REGENERATE_COMMAND . '` from ' . $source . '. Do not edit this file: change the declaration and regenerate. -->';
	}

	/**
	 * Describes a field: its type and constraints, whether it may be null, its default and its privacy.
	 *
	 * @since 0.1.0
	 *
	 * @param FieldSpec $field     The field.
	 * @param bool      $is_output Whether the field is part of an output rather than an input.
	 * @return string One or more sentences.
	 */
	public static function describe( FieldSpec $field, bool $is_output ): string {
		$sentences = array( self::type( $field ) );

		if ( $field->isNullable() ) {
			$sentences[] = 'May be null.';
		}

		if ( null !== $field->defaultValue() ) {
			$sentences[] = self::defaultValue( (string) $field->defaultValue() );
		}

		if ( Privacy::Pii === $field->privacy() ) {
			$sentences[] = $is_output
				? 'Personal data: returned only to a user who holds the capability `' . OperationInvoker::PERSONAL_DATA_CAPABILITY . '`.'
				: 'Personal data.';
		} elseif ( Privacy::Secret === $field->privacy() ) {
			$sentences[] = 'Secret: accepted, never returned.';
		}

		return implode( ' ', $sentences );
	}

	/**
	 * Describes a closed set of values.
	 *
	 * @since 0.1.0
	 *
	 * @param string[] $values The values.
	 * @return string The sentence.
	 */
	public static function values( array $values ): string {
		return 'One of ' . implode( ', ', array_map( static fn( string $value ): string => '`' . $value . '`', $values ) ) . '.';
	}

	/**
	 * Describes a default.
	 *
	 * @since 0.1.0
	 *
	 * @param string $value The default.
	 * @return string The sentence.
	 */
	public static function defaultValue( string $value ): string {
		return 'Default `' . $value . '`.';
	}

	/**
	 * Lists the facts every surface of an operation shares: its id, capability and error codes.
	 *
	 * @since 0.1.0
	 *
	 * @param OperationDefinition $definition The operation.
	 * @param ErrorTable          $errors     The error table, for each code's status.
	 * @return list<string> Markdown list items.
	 */
	public static function operationFacts( OperationDefinition $definition, ErrorTable $errors ): array {
		$codes = array();

		foreach ( self::errorCodes( $definition, $errors ) as $code ) {
			$codes[] = '`' . $code->value . '` (' . $errors->definitionFor( $code )->httpStatus() . ')';
		}

		return array(
			'- Operation: `' . $definition->id() . '`',
			'- Capability: ' . self::capability( $definition ),
			'- Error codes: ' . ( array() === $codes ? 'none' : implode( ', ', $codes ) ),
		);
	}

	/**
	 * Lists the codes an operation can answer with: the ones it declares, and, when it changes the
	 * store, every code whose row says any write may raise it.
	 *
	 * @since 0.1.0
	 *
	 * @param OperationDefinition $definition The operation.
	 * @param ErrorTable          $errors     The error table.
	 * @return list<ErrorCode> The declared codes in their order, then the others in code order.
	 */
	public static function errorCodes( OperationDefinition $definition, ErrorTable $errors ): array {
		$codes = $definition->errors();

		if ( $definition->annotations()->isReadOnly() ) {
			return $codes;
		}

		foreach ( $errors->definitions() as $row ) {
			if ( $row->isAnyWrite() && ! in_array( $row->code(), $codes, true ) ) {
				$codes[] = $row->code();
			}
		}

		return $codes;
	}

	/**
	 * Names the capability an operation requires.
	 *
	 * @since 0.1.0
	 *
	 * @param OperationDefinition $definition The operation.
	 * @return string The capability, and the input that names the resource when it is checked on one.
	 */
	public static function capability( OperationDefinition $definition ): string {
		$field = $definition->resourceField();

		return '`' . $definition->capability() . '`' . ( null === $field ? '' : ' on the resource that `' . $field . '` names' );
	}

	/**
	 * Describes a field's type and constraints.
	 *
	 * @since 0.1.0
	 *
	 * @param FieldSpec $field The field.
	 * @return string The sentence.
	 */
	private static function type( FieldSpec $field ): string {
		if ( FieldType::Uuid === $field->type() ) {
			return 'A uuid.';
		}

		if ( FieldType::Integer === $field->type() ) {
			$minimum = $field->minimum();
			$maximum = $field->maximum();

			if ( null !== $minimum && null !== $maximum ) {
				return 'An integer from ' . $minimum . ' to ' . $maximum . '.';
			}

			if ( null !== $minimum ) {
				return 'An integer of at least ' . $minimum . '.';
			}

			return null === $maximum ? 'An integer.' : 'An integer of at most ' . $maximum . '.';
		}

		if ( array() !== $field->allowedValues() ) {
			return self::values( $field->allowedValues() );
		}

		return null === $field->maxLength() ? 'Text.' : 'Text of at most ' . $field->maxLength() . ' characters.';
	}
}
